#!/bin/sh
. "$HOME/.scripts/config"
alias mpc="mpc -h /tmp/mpd.unix -f %file%"
while :
do
    playing="$(mpc | head -n1)"
    mpc idle
    nplaying="$(mpc | head -n1)"

    if [ "$nplaying" != "$playing" ]; then
        if [ ! -z "$playing" ]; then
            echo "Moving to old"
            ~/.scripts/music/move_to_old "$SOULSEEK_DOWNLOAD_PATH/Old" "$playing"
        fi
    fi
    sleep 0.5
done
