#!/bin/sh
. "$HOME/.scripts/config"
find "$SOULSEEK_DOWNLOAD_PATH" -type d | grep -v 'Old' |\
    parallel -q -j100 -I {} iwatch -v -e close_nowrite -c "sh ~/.scripts/music/move_to_old $SOULSEEK_DOWNLOAD_PATH/Old %f" "{}"
