#!/bin/sh
set -e
. ~/.scripts/bluetooth/config

IFS=$'\n'
LOCK=/tmp/bluetoothDisconnect.lock
choice="$(echo  "$DEVICES" | cut -d" " -f2-99 | wofi -dmenu)"

[ -z "$choice" ] && exit

mac="$(echo "$DEVICES" | grep "$choice" | cut -d" " -f1)"

[ -f "$LOCK" ]  && {
    notify-send "Bluetooth" "Already trying to connect"
    exit
}

bluetoothctl power on

touch "$LOCK"

notify-send "Bluetooth" "Trying to connect to $choice"

bluetoothctl connect "$mac" || {
    notify-send "Bluetooth" "Failed to connect"
    rm "$LOCK"
    exit
}

notify-send "Bluetooth" "Bluetooth connected"
rm "$LOCK"
