#!/bin/sh
set -e
. ~/.scripts/bluetooth/config
LOCK=/tmp/bluetoothConnect.lock

[ -f "$LOCK" ] && {
    notify-send "Bluetooth" "Already trying to disconnect"
    exit
}

touch "$LOCK"

notify-send "Bluetooth" "Trying to disconnect from $(bluetoothctl info  | grep Name | cut -d":" -f2)"

bluetoothctl disconnect "$(bluetoothctl info | grep Device  | cut -d" " -f2 | head -n1)" || {
    notify-send "Bluetooth" "Failed to disconnect"
    rm "$LOCK"
    exit
}

notify-send "Bluetooth" "Bluetooth disconnected"
rm "$LOCK"
