#!/bin/sh
choice="$(find "$HOME/.password-store" -iname '*.gpg' | sed -e 's/.*password-store\///g' | sed -e 's/\.gpg$//g' | wofi -dmenu)"
[ -z "$choice" ] && exit
pass -c "$choice"
notify-send "Password" "Copied password for $choice"
