#!/bin/sh
input="$(find "$HOME/.password-store" -iname '*.gpg' | sed -e 's/.*password-store\///g' | sed -e 's/\.gpg$//g' | wofi -dmenu -p "Source: ")"
[ -z "$input" ] && exit

output="$(wofi -dmenu -p "Destination: ")"
[ -z "$output" ] && exit

pass mv "$input" "$output"
notify-send "Password" "Moved $input to $output"
