#!/bin/sh

alacritty -e sh -c 'sudo modprobe v4l2loopback exclusive_caps=1 card_label=WfRecorder && wf-recorder -g "$(slurp)" --muxer=v4l2 --codec=rawvideo --file=$(v4l2-ctl --list-devices | awk "BEGIN{i=0} i == 1{print \$1; exit} /WfRecorder/{i=1}") -x yuv420p'
